// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class KongaTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginwithblankusernamevalidpassword() {
    // Test name: Login-with-blank-username-valid-password
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | mouseOver | css=.\_41783_2ijjb:nth-child(7) > picture | 
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_41783_2ijjb:nth-child(7) > picture"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | css=.\_41783_2ijjb:nth-child(7) > picture | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 6 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 7 | type | id=password | testings
    driver.findElement(By.id("password")).sendKeys("testings");
    // 8 | click | css=.\_988cf_1aDdJ | 
    driver.findElement(By.cssSelector(".\\_988cf_1aDdJ")).click();
    // 9 | click | css=.\_40e43_1f83p > span | 
    driver.findElement(By.cssSelector(".\\_40e43_1f83p > span")).click();
    // 10 | close |  | 
    driver.close();
  }
  @Test
  public void loginpasswordlessthancharacter() {
    // Test name: Login-password-less-than-character
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | mouseOver | css=div > a > picture > .lazyloaded | 
    {
      WebElement element = driver.findElement(By.cssSelector("div > a > picture > .lazyloaded"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | css=div > a > picture > .lazyloaded | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 6 | mouseOver | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.linkText("Login / Signup"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | mouseOut | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 8 | click | id=username | 
    driver.findElement(By.id("username")).click();
    // 9 | type | id=username | stephabuts@gmail,com
    driver.findElement(By.id("username")).sendKeys("stephabuts@gmail,com");
    // 10 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 11 | type | id=password | umbur
    driver.findElement(By.id("password")).sendKeys("umbur");
    // 12 | click | css=.\_988cf_1aDdJ | 
    driver.findElement(By.cssSelector(".\\_988cf_1aDdJ")).click();
    // 13 | click | css=.\_9a1ab_k0UMi:nth-child(4) | 
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(4)")).click();
    // 14 | verifyText | css=.\_9a1ab_k0UMi:nth-child(4) | The password must be at least 6 characters
    assertThat(driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(4)")).getText(), is("The password must be at least 6 characters"));
    // 15 | click | linkText=Close | 
    driver.findElement(By.linkText("Close")).click();
    // 16 | close |  | 
    driver.close();
  }
  @Test
  public void loginwithwrongusernamewrongpassword() {
    // Test name: Login-with-wrong-username-wrong-password
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | mouseOver | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.linkText("Login / Signup"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 5 | mouseOut | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | click | id=username | 
    driver.findElement(By.id("username")).click();
    // 7 | type | id=username | stevv.com
    driver.findElement(By.id("username")).sendKeys("stevv.com");
    // 8 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 9 | type | id=password | suhagets
    driver.findElement(By.id("password")).sendKeys("suhagets");
    // 10 | click | css=.\_988cf_1aDdJ | 
    driver.findElement(By.cssSelector(".\\_988cf_1aDdJ")).click();
    // 11 | click | css=.\_40e43_1f83p > span | 
    driver.findElement(By.cssSelector(".\\_40e43_1f83p > span")).click();
    // 12 | close |  | 
    driver.close();
  }
  @Test
  public void loginwithunregisteredemail() {
    // Test name: Login-with-unregistered-email
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 4 | click | id=username | 
    driver.findElement(By.id("username")).click();
    // 5 | type | id=username | umbur@qa.team
    driver.findElement(By.id("username")).sendKeys("umbur@qa.team");
    // 6 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 7 | type | id=password | uisetugs
    driver.findElement(By.id("password")).sendKeys("uisetugs");
    // 8 | click | css=.\_988cf_1aDdJ | 
    driver.findElement(By.cssSelector(".\\_988cf_1aDdJ")).click();
    // 9 | click | css=.\_71d30_2oCCX | 
    driver.findElement(By.cssSelector(".\\_71d30_2oCCX")).click();
    // 10 | verifyText | css=.\_9a1ab_k0UMi:nth-child(3) | The username or password you have entered is incorrect. Please try again.
    assertThat(driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).getText(), is("The username or password you have entered is incorrect. Please try again."));
    // 11 | click | css=.\_40e43_1f83p > span | 
    driver.findElement(By.cssSelector(".\\_40e43_1f83p > span")).click();
    // 12 | close |  | 
    driver.close();
  }
  @Test
  public void loginwithvalidusernameandwrongpassword() {
    // Test name: Login-with-valid-username-and-wrong-password
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | mouseOver | css=div > a > picture > .lazyloaded | 
    {
      WebElement element = driver.findElement(By.cssSelector("div > a > picture > .lazyloaded"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | css=div > a > picture > .lazyloaded | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 6 | click | id=username | 
    driver.findElement(By.id("username")).click();
    // 7 | type | id=username | stephabuts@qa.team
    driver.findElement(By.id("username")).sendKeys("stephabuts@qa.team");
    // 8 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 9 | type | id=password | gurutest
    driver.findElement(By.id("password")).sendKeys("gurutest");
    // 10 | click | css=.\_988cf_1aDdJ | 
    driver.findElement(By.cssSelector(".\\_988cf_1aDdJ")).click();
    // 11 | click | css=.\_0a76d_2_hrl:nth-child(2) | 
    driver.findElement(By.cssSelector(".\\_0a76d_2_hrl:nth-child(2)")).click();
    // 12 | click | css=.\_9a1ab_k0UMi:nth-child(3) | 
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    // 13 | click | css=.\_9a1ab_k0UMi:nth-child(3) | 
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    // 14 | doubleClick | css=.\_9a1ab_k0UMi:nth-child(3) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 15 | verifyText | css=.\_9a1ab_k0UMi:nth-child(3) | The username or password you have entered is incorrect. Please try again.
    assertThat(driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).getText(), is("The username or password you have entered is incorrect. Please try again."));
    // 16 | click | css=.\_40e43_1f83p > svg | 
    driver.findElement(By.cssSelector(".\\_40e43_1f83p > svg")).click();
    // 17 | close |  | 
    driver.close();
  }
  @Test
  public void loginwithvalidusernameblankpassword() {
    // Test name: Login-with-valid-username-blank-password
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 4 | click | id=username | 
    driver.findElement(By.id("username")).click();
    // 5 | type | id=username | stephabuts@qa.team
    driver.findElement(By.id("username")).sendKeys("stephabuts@qa.team");
    // 6 | click | css=.\_988cf_1aDdJ | blank 
    // no input
    driver.findElement(By.cssSelector(".\\_988cf_1aDdJ")).click();
    // 7 | click | linkText=Close | 
    driver.findElement(By.linkText("Close")).click();
    // 8 | close |  | 
    driver.close();
  }
  @Test
  public void loginwithoutclickingloginbutton() {
    // Test name: Login-without-clicking-loginbutton
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 4 | click | id=username | 
    driver.findElement(By.id("username")).click();
    // 5 | type | id=username | stephabuts@qa.team
    driver.findElement(By.id("username")).sendKeys("stephabuts@qa.team");
    // 6 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 7 | type | id=password | testings
    driver.findElement(By.id("password")).sendKeys("testings");
    // 8 | click | css=.\_40e43_1f83p > span | 
    driver.findElement(By.cssSelector(".\\_40e43_1f83p > span")).click();
    // 9 | close |  | 
    driver.close();
  }
  @Test
  public void forgotpasswordlinksent() {
    // Test name: Forgot-password-link-sent
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 4 | click | linkText=Forgot Password? | 
    driver.findElement(By.linkText("Forgot Password?")).click();
    // 5 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 6 | type | id=email | stephabuts@qa.team
    driver.findElement(By.id("email")).sendKeys("stephabuts@qa.team");
    // 7 | click | css=.fd68f_3wAfg | 
    driver.findElement(By.cssSelector(".fd68f_3wAfg")).click();
    // 8 | close |  | 
    driver.close();
  }
  @Test
  public void forgotpasswordwithblankfield() {
    // Test name: Forgot-password-with-blank-field
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | mouseOver | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.linkText("Login / Signup"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 5 | mouseOut | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | click | linkText=Forgot Password? | 
    driver.findElement(By.linkText("Forgot Password?")).click();
    // 7 | click | css=.fd68f_3wAfg | 
    driver.findElement(By.cssSelector(".fd68f_3wAfg")).click();
    // 8 | close |  | 
    driver.close();
  }
  @Test
  public void forgotpasswordwithoutclickingsendresetbutton() {
    // Test name: Forgot-password-without-clicking-sendresetbutton
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | mouseOver | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.linkText("Login / Signup"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 5 | mouseOut | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | click | linkText=Forgot Password? | 
    driver.findElement(By.linkText("Forgot Password?")).click();
    // 7 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 8 | type | id=email | stephabuts@qa.team
    driver.findElement(By.id("email")).sendKeys("stephabuts@qa.team");
    // 9 | close |  | 
    driver.close();
  }
  @Test
  public void forgotpasswordwithunregisteredemail() {
    // Test name: Forgot-password-with-unregistered-email
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 4 | mouseOver | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.linkText("Login / Signup"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 5 | mouseOut | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | click | linkText=Forgot Password? | 
    driver.findElement(By.linkText("Forgot Password?")).click();
    // 7 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 8 | type | id=email | umbur@qa.team
    driver.findElement(By.id("email")).sendKeys("umbur@qa.team");
    // 9 | click | css=.fd68f_3wAfg | 
    driver.findElement(By.cssSelector(".fd68f_3wAfg")).click();
    // 10 | click | css=.\_869ee_1ewC4 | 
    driver.findElement(By.cssSelector(".\\_869ee_1ewC4")).click();
    // 11 | verifyText | css=.e2c5a_3U4MA | We could not initiate password reset for your email: umbur@qa.team. Please check that the address is valid and try again
    assertThat(driver.findElement(By.cssSelector(".e2c5a_3U4MA")).getText(), is("We could not initiate password reset for your email: umbur@qa.team. Please check that the address is valid and try again"));
    // 12 | close |  | 
    driver.close();
  }
  @Test
  public void forgotpasswordwithwrongemail() {
    // Test name: Forgot-password-with-wrong-email
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 4 | click | linkText=Forgot Password? | 
    driver.findElement(By.linkText("Forgot Password?")).click();
    // 5 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 6 | type | id=email | umbur@gmail.com
    driver.findElement(By.id("email")).sendKeys("umbur@gmail.com");
    // 7 | click | css=.fd68f_3wAfg | 
    driver.findElement(By.cssSelector(".fd68f_3wAfg")).click();
    // 8 | click | css=.e2c5a_3U4MA | 
    driver.findElement(By.cssSelector(".e2c5a_3U4MA")).click();
    // 9 | click | css=.e2c5a_3U4MA | 
    driver.findElement(By.cssSelector(".e2c5a_3U4MA")).click();
    // 10 | click | css=.\_869ee_1ewC4 | 
    driver.findElement(By.cssSelector(".\\_869ee_1ewC4")).click();
    // 11 | verifyText | css=.\_869ee_1ewC4 | We could not initiate password reset for your email: umbur@gmail.com. Please check that the address is valid and try again
    assertThat(driver.findElement(By.cssSelector(".\\_869ee_1ewC4")).getText(), is("We could not initiate password reset for your email: umbur@gmail.com. Please check that the address is valid and try again"));
    // 12 | close |  | 
    driver.close();
  }
  @Test
  public void forgotpasswordwithincompleteemail() {
    // Test name: Forgot-password-with-incomplete-email
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1346x708 | 
    driver.manage().window().setSize(new Dimension(1346, 708));
    // 3 | mouseOver | css=div > a > picture > .lazyloaded | 
    {
      WebElement element = driver.findElement(By.cssSelector("div > a > picture > .lazyloaded"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | css=div > a > picture > .lazyloaded | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 6 | click | css=.\_0a76d_2_hrl:nth-child(2) | 
    driver.findElement(By.cssSelector(".\\_0a76d_2_hrl:nth-child(2)")).click();
    // 7 | click | linkText=Forgot Password? | 
    driver.findElement(By.linkText("Forgot Password?")).click();
    // 8 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 9 | type | id=email | steph@.team
    driver.findElement(By.id("email")).sendKeys("steph@.team");
    // 10 | click | css=.fd68f_3wAfg | 
    driver.findElement(By.cssSelector(".fd68f_3wAfg")).click();
    // 11 | close |  | 
    driver.close();
  }
  @Test
  public void signupwithwrongdetailsnameemailpasswordphone() {
    // Test name: Signup with-wrong-details-name/email/password/phone#
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 4 | click | linkText=Don’t have an account? Sign Up | 
    driver.findElement(By.linkText("Don’t have an account? Sign Up")).click();
    // 5 | click | id=firstname | 
    driver.findElement(By.id("firstname")).click();
    // 6 | type | id=firstname | pppp
    driver.findElement(By.id("firstname")).sendKeys("pppp");
    // 7 | click | id=lastname | 
    driver.findElement(By.id("lastname")).click();
    // 8 | type | id=lastname | kkk
    driver.findElement(By.id("lastname")).sendKeys("kkk");
    // 9 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 10 | type | id=email | hhhh@.com
    driver.findElement(By.id("email")).sendKeys("hhhh@.com");
    // 11 | click | id=phone | 
    driver.findElement(By.id("phone")).click();
    // 12 | type | id=phone | 00000001234
    driver.findElement(By.id("phone")).sendKeys("00000001234");
    // 13 | click | css=.\_460b6_SNRLa > #password | 
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa > #password")).click();
    // 14 | type | css=.\_460b6_SNRLa > #password | postings
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa > #password")).sendKeys("postings");
    // 15 | click | css=.\_2f3a3_3JCsL | 
    driver.findElement(By.cssSelector(".\\_2f3a3_3JCsL")).click();
    // 16 | close |  | 
    driver.close();
  }
  @Test
  public void signupwith10numbersonlypassword() {
    // Test name: Signup-with-10-numbers-only-password
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | mouseOver | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.linkText("Login / Signup"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 5 | mouseOut | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | mouseOver | id=google_container | 
    {
      WebElement element = driver.findElement(By.id("google_container"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | mouseOver | linkText=Don’t have an account? Sign Up | 
    {
      WebElement element = driver.findElement(By.linkText("Don’t have an account? Sign Up"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 8 | click | linkText=Don’t have an account? Sign Up | 
    driver.findElement(By.linkText("Don’t have an account? Sign Up")).click();
    // 9 | mouseOut | css=.\_1dce2_MjLDv > a | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 10 | click | id=firstname | 
    driver.findElement(By.id("firstname")).click();
    // 11 | type | id=firstname | stephanie
    driver.findElement(By.id("firstname")).sendKeys("stephanie");
    // 12 | click | id=lastname | 
    driver.findElement(By.id("lastname")).click();
    // 13 | type | id=lastname | mkar
    driver.findElement(By.id("lastname")).sendKeys("mkar");
    // 14 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 15 | type | id=email | stephabuts@qa.team
    driver.findElement(By.id("email")).sendKeys("stephabuts@qa.team");
    // 16 | click | id=phone | 
    driver.findElement(By.id("phone")).click();
    // 17 | type | id=phone | 08095444150
    driver.findElement(By.id("phone")).sendKeys("08095444150");
    // 18 | click | css=.\_460b6_SNRLa > #password | 
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa > #password")).click();
    // 19 | type | css=.\_460b6_SNRLa > #password | 1234567898
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa > #password")).sendKeys("1234567898");
    // 20 | click | css=.\_2f3a3_3JCsL | 
    driver.findElement(By.cssSelector(".\\_2f3a3_3JCsL")).click();
    // 21 | close |  | 
    driver.close();
  }
  @Test
  public void signupwithblankemail() {
    // Test name: Signup-with-blank-email
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 4 | mouseOver | css=.\_0af66_1C18Y | 
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_0af66_1C18Y"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 5 | click | linkText=Don’t have an account? Sign Up | 
    driver.findElement(By.linkText("Don’t have an account? Sign Up")).click();
    // 6 | click | id=firstname | 
    driver.findElement(By.id("firstname")).click();
    // 7 | type | id=firstname | umbue
    driver.findElement(By.id("firstname")).sendKeys("umbue");
    // 8 | click | id=lastname | 
    driver.findElement(By.id("lastname")).click();
    // 9 | type | id=lastname | biko
    driver.findElement(By.id("lastname")).sendKeys("biko");
    // 10 | click | id=phone | 
    driver.findElement(By.id("phone")).click();
    // 11 | type | id=phone | 09085441640
    driver.findElement(By.id("phone")).sendKeys("09085441640");
    // 12 | click | css=.\_460b6_SNRLa > #password | 
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa > #password")).click();
    // 13 | type | css=.\_460b6_SNRLa > #password | testingtaws
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa > #password")).sendKeys("testingtaws");
    // 14 | click | css=.\_2f3a3_3JCsL | 
    driver.findElement(By.cssSelector(".\\_2f3a3_3JCsL")).click();
    // 15 | close |  | 
    driver.close();
  }
  @Test
  public void signupwithblankfieldsforname() {
    // Test name: Signup-with-blank-fields-for-name
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 4 | mouseOver | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.linkText("Login / Signup"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 5 | mouseOut | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | click | css=.\_1dce2_MjLDv | 
    driver.findElement(By.cssSelector(".\\_1dce2_MjLDv")).click();
    // 7 | mouseOver | linkText=Don’t have an account? Sign Up | 
    {
      WebElement element = driver.findElement(By.linkText("Don’t have an account? Sign Up"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 8 | click | linkText=Don’t have an account? Sign Up | 
    driver.findElement(By.linkText("Don’t have an account? Sign Up")).click();
    // 9 | mouseOut | css=.\_1dce2_MjLDv > a | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 10 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 11 | type | id=email | stephabuts@qa.team
    driver.findElement(By.id("email")).sendKeys("stephabuts@qa.team");
    // 12 | click | id=phone | 
    driver.findElement(By.id("phone")).click();
    // 13 | type | id=phone | 07065007400
    driver.findElement(By.id("phone")).sendKeys("07065007400");
    // 14 | click | css=.\_460b6_SNRLa > #password | 
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa > #password")).click();
    // 15 | type | css=.\_460b6_SNRLa > #password | testings
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa > #password")).sendKeys("testings");
    // 16 | click | css=.\_2f3a3_3JCsL | 
    driver.findElement(By.cssSelector(".\\_2f3a3_3JCsL")).click();
    // 17 | close |  | 
    driver.close();
  }
  @Test
  public void signupwithblankfieldsnameemialpasswordphone() {
    // Test name: Signup-with-blank-fields-name/emial/password/phone#
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | mouseOver | css=.e69c3_LLZb4:nth-child(1) .f5e10_VzEXF | 
    {
      WebElement element = driver.findElement(By.cssSelector(".e69c3_LLZb4:nth-child(1) .f5e10_VzEXF"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | css=.e69c3_LLZb4:nth-child(1) .f5e10_VzEXF | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | mouseOver | linkText=Baby, Kids and Toys | 
    {
      WebElement element = driver.findElement(By.linkText("Baby, Kids and Toys"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | mouseOut | linkText=Baby, Kids and Toys | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 7 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 8 | mouseOver | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.linkText("Login / Signup"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | mouseOut | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 10 | mouseOver | linkText=Don’t have an account? Sign Up | 
    {
      WebElement element = driver.findElement(By.linkText("Don’t have an account? Sign Up"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 11 | click | linkText=Don’t have an account? Sign Up | 
    driver.findElement(By.linkText("Don’t have an account? Sign Up")).click();
    // 12 | mouseOut | css=.\_1dce2_MjLDv > a | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 13 | click | css=.\_2f3a3_3JCsL | 
    driver.findElement(By.cssSelector(".\\_2f3a3_3JCsL")).click();
    // 14 | mouseOver | linkText=Show | 
    {
      WebElement element = driver.findElement(By.linkText("Show"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 15 | close |  | 
    driver.close();
  }
  @Test
  public void signupwithblankpassword() {
    // Test name: Signup-with-blank-password
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 4 | click | linkText=Don’t have an account? Sign Up | 
    driver.findElement(By.linkText("Don’t have an account? Sign Up")).click();
    // 5 | click | id=firstname | 
    driver.findElement(By.id("firstname")).click();
    // 6 | type | id=firstname | mmk
    driver.findElement(By.id("firstname")).sendKeys("mmk");
    // 7 | click | id=lastname | 
    driver.findElement(By.id("lastname")).click();
    // 8 | type | id=lastname | syet
    driver.findElement(By.id("lastname")).sendKeys("syet");
    // 9 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 10 | type | id=email | stephabuts@qa.team
    driver.findElement(By.id("email")).sendKeys("stephabuts@qa.team");
    // 11 | click | id=phone | 
    driver.findElement(By.id("phone")).click();
    // 12 | type | id=phone | 08037412233
    driver.findElement(By.id("phone")).sendKeys("08037412233");
    // 13 | click | css=.\_2f3a3_3JCsL | 
    driver.findElement(By.cssSelector(".\\_2f3a3_3JCsL")).click();
    // 14 | close |  | 
    driver.close();
  }
  @Test
  public void signupwithinvalidcode() {
    // Test name: Signup-with-invalid-code
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | mouseOver | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.linkText("Login / Signup"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 5 | mouseOut | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | click | id=username | 
    driver.findElement(By.id("username")).click();
    // 7 | click | linkText=Don’t have an account? Sign Up | 
    driver.findElement(By.linkText("Don’t have an account? Sign Up")).click();
    // 8 | click | id=firstname | 
    driver.findElement(By.id("firstname")).click();
    // 9 | type | id=firstname | baby
    driver.findElement(By.id("firstname")).sendKeys("baby");
    // 10 | click | id=lastname | 
    driver.findElement(By.id("lastname")).click();
    // 11 | type | id=lastname | me
    driver.findElement(By.id("lastname")).sendKeys("me");
    // 12 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 13 | type | id=email | stephabuts@qa.team
    driver.findElement(By.id("email")).sendKeys("stephabuts@qa.team");
    // 14 | click | id=phone | 
    driver.findElement(By.id("phone")).click();
    // 15 | type | id=phone | 08036007400
    driver.findElement(By.id("phone")).sendKeys("08036007400");
    // 16 | click | css=.\_460b6_SNRLa > #password | 
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa > #password")).click();
    // 17 | type | css=.\_460b6_SNRLa > #password | testings1
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa > #password")).sendKeys("testings1");
    // 18 | click | css=.\_2f3a3_3JCsL | 
    driver.findElement(By.cssSelector(".\\_2f3a3_3JCsL")).click();
    // 19 | click | id=phone | 
    driver.findElement(By.id("phone")).click();
    // 20 | type | id=phone | 08036007100
    driver.findElement(By.id("phone")).sendKeys("08036007100");
    // 21 | click | css=.\_2f3a3_3JCsL | 
    driver.findElement(By.cssSelector(".\\_2f3a3_3JCsL")).click();
    // 22 | click | id=pin | 
    driver.findElement(By.id("pin")).click();
    // 23 | click | id=pin | 
    driver.findElement(By.id("pin")).click();
    // 24 | type | id=pin | 0000
    driver.findElement(By.id("pin")).sendKeys("0000");
    // 25 | click | css=.\_83d7e_2rg5_ | 
    driver.findElement(By.cssSelector(".\\_83d7e_2rg5_")).click();
    // 26 | mouseOver | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.linkText("Login / Signup"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 27 | mouseOut | linkText=Login / Signup | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 28 | close |  | 
    driver.close();
  }
  @Test
  public void signupwithinvalidemail() {
    // Test name: Signup-with-invalid-email
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | mouseOver | css=div > a > picture > .lazyloaded | 
    {
      WebElement element = driver.findElement(By.cssSelector("div > a > picture > .lazyloaded"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | css=div > a > picture > .lazyloaded | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 6 | click | linkText=Don’t have an account? Sign Up | 
    driver.findElement(By.linkText("Don’t have an account? Sign Up")).click();
    // 7 | click | id=firstname | 
    driver.findElement(By.id("firstname")).click();
    // 8 | type | id=firstname | meme
    driver.findElement(By.id("firstname")).sendKeys("meme");
    // 9 | click | id=lastname | 
    driver.findElement(By.id("lastname")).click();
    // 10 | type | id=lastname | tete
    driver.findElement(By.id("lastname")).sendKeys("tete");
    // 11 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 12 | type | id=email | steph.team
    driver.findElement(By.id("email")).sendKeys("steph.team");
    // 13 | click | id=phone | 
    driver.findElement(By.id("phone")).click();
    // 14 | type | id=phone | 07064005400
    driver.findElement(By.id("phone")).sendKeys("07064005400");
    // 15 | click | css=.\_460b6_SNRLa > #password | 
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa > #password")).click();
    // 16 | type | css=.\_460b6_SNRLa > #password | testints1
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa > #password")).sendKeys("testints1");
    // 17 | click | css=.\_2f3a3_3JCsL | 
    driver.findElement(By.cssSelector(".\\_2f3a3_3JCsL")).click();
    // 18 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 19 | type | id=email | steph.@team
    driver.findElement(By.id("email")).sendKeys("steph.@team");
    // 20 | click | css=.\_2f3a3_3JCsL | 
    driver.findElement(By.cssSelector(".\\_2f3a3_3JCsL")).click();
    // 21 | click | css=.\_460b6_SNRLa:nth-child(4) > .c1ba4_2Fcv7 | 
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa:nth-child(4) > .c1ba4_2Fcv7")).click();
    // 22 | click | css=.\_460b6_SNRLa:nth-child(4) > .c1ba4_2Fcv7 | 
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa:nth-child(4) > .c1ba4_2Fcv7")).click();
    // 23 | verifyText | css=.\_460b6_SNRLa:nth-child(4) > .c1ba4_2Fcv7 | The email must be a valid email
    assertThat(driver.findElement(By.cssSelector(".\\_460b6_SNRLa:nth-child(4) > .c1ba4_2Fcv7")).getText(), is("The email must be a valid email"));
    // 24 | close |  | 
    driver.close();
  }
  @Test
  public void signupwithrequiredfields() {
    // Test name: Signup-with-required-fields
    // Step # | name | target | value
    // 1 | open | https://www.konga.com/ | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | linkText=Login / Signup | 
    driver.findElement(By.linkText("Login / Signup")).click();
    // 4 | click | linkText=Don’t have an account? Sign Up | 
    driver.findElement(By.linkText("Don’t have an account? Sign Up")).click();
    // 5 | click | id=firstname | 
    driver.findElement(By.id("firstname")).click();
    // 6 | type | id=firstname | umbur
    driver.findElement(By.id("firstname")).sendKeys("umbur");
    // 7 | click | css=.\_460b6_SNRLa:nth-child(3) | 
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa:nth-child(3)")).click();
    // 8 | click | id=lastname | 
    driver.findElement(By.id("lastname")).click();
    // 9 | type | id=lastname | mkar
    driver.findElement(By.id("lastname")).sendKeys("mkar");
    // 10 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 11 | type | id=email | umburabutu@gmail.com
    driver.findElement(By.id("email")).sendKeys("umburabutu@gmail.com");
    // 12 | click | id=phone | 
    driver.findElement(By.id("phone")).click();
    // 13 | type | id=phone | 07036007400
    driver.findElement(By.id("phone")).sendKeys("07036007400");
    // 14 | click | css=.\_460b6_SNRLa > #password | 
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa > #password")).click();
    // 15 | type | css=.\_460b6_SNRLa > #password | umbusco
    driver.findElement(By.cssSelector(".\\_460b6_SNRLa > #password")).sendKeys("umbusco");
    // 16 | click | css=.\_2f3a3_3JCsL | 
    driver.findElement(By.cssSelector(".\\_2f3a3_3JCsL")).click();
    // 17 | click | id=pin | 
    driver.findElement(By.id("pin")).click();
    // 18 | type | id=pin | 7778
    driver.findElement(By.id("pin")).sendKeys("7778");
    // 19 | click | css=.\_83d7e_2rg5_ | 
    driver.findElement(By.cssSelector(".\\_83d7e_2rg5_")).click();
    // 20 | mouseOver | css=.\_73477_1JLsr | 
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_73477_1JLsr"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 21 | mouseOut | css=.\_73477_1JLsr | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 22 | close |  | 
    driver.close();
  }
}
